# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17nSP7rcikYMbdMV6-rWi3Tdtwysrv5BX
"""

import requests
print(requests.__version__)

!pip install -q langchain langchain-groq langchain-community newsapi-python python-dotenv

!pip install langchain-community --no-deps
!pip install langchain-core langchain-groq langchain-openai langchain-text-splitters --quiet

!pip install streamlit -q

# app.py

import streamlit as st
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
from langchain_groq import ChatGroq
from newsapi import NewsApiClient

# Step 1: Your API Keys (Replace with your real ones)
groq_api_key = "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"
newsapi_key = "12262d1298f14a69b7e4775947fda76b"

# Step 2: Initialize LLM and News API
llm = ChatGroq(api_key=groq_api_key, model="llama3-8b-8192")
newsapi = NewsApiClient(api_key=newsapi_key)

# Step 3: Functions to get and summarize news
def get_news_articles(query):
    articles = newsapi.get_everything(q=query, language='en', sort_by='relevancy', page_size=5)
    return articles['articles']

def summarize_articles(articles):
    return ' '.join([a['description'] for a in articles if a['description']])

def get_summary(query):
    articles = get_news_articles(query)
    return summarize_articles(articles)

# Step 4: Prompt Template
template = """
You are an AI assistant helping an equity research analyst.
Given the following query and the provided news article summaries, provide a concise summary.

Query: {query}
Summaries: {summaries}
"""

prompt = PromptTemplate(template=template, input_variables=["query", "summaries"])
llm_chain = LLMChain(prompt=prompt, llm=llm)

# Step 5: Streamlit UI
st.title("Global Research News Tool")
query = st.text_input("Enter your query (e.g., Apple stock, Tesla earnings)")

if st.button("Get News Summary"):
    if query:
        summaries = get_summary(query)
        response = llm_chain.run({"query": query, "summaries": summaries})
        st.subheader("📰 Summary:")
        st.write(response)
    else:
        st.warning("Please enter a query.")

!pip install streamlit pyngrok

from pyngrok import ngrok

# Paste your actual token below (this is just an example!)
ngrok.set_auth_token("33KTKlv357waRgMYPPh0yKke7m7_7iFdLUQE5JZ5ineUq8sdx")

# Commented out IPython magic to ensure Python compatibility.
# # Write your Streamlit app
# %%writefile app.py
# import streamlit as st
# 
# st.title("Hello from Streamlit in Colab!")
# name = st.text_input("What's your name?")
# if name:
#     st.success(f"Hi, {name}! 👋")

from pyngrok import ngrok
from google.colab import userdata

# Start the Streamlit app
!streamlit run app.py &

# Create ngrok tunnel
public_url = ngrok.connect(port=8501)
print(f"🌐 Streamlit app is live at: {public_url}")